series: Basic C++
title: Virtual Functions
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Virtual functions are an important part of object-oriented programming.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Inheritance
  - series: Basic C++
    title: The Stack and the Heap
  - series: Basic C++
    title: Overloading